services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/init-multiple-databases-and-users.sql:/docker-entrypoint-initdb.d/init-multiple-databases-and-users.sql

volumes:
  postgres_data:
