db_name: gym_prod_db
db_password: ${prod_password}
db_username: ${prod_username}

server:
  port: 8081
springdoc:
  api-docs:
    enabled: false
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        exclude: '*'