server:
  servlet:
    context-path: /gym
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${db_password}
    url: jdbc:postgresql://localhost:5432/${db_name}
    username: ${db_username}
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
    password: ${db_password}
    url: jdbc:postgresql://localhost:5432/${db_name}
    user: ${db_username}
  jpa:
    database: postgresql
    show-sql: false
jwt:
  secret: ${jwt_secret}
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  level:
    org:
      example: debug
      hibernate:
        resource: error
      springframework:
        security: debug
    root: info
