server:
  servlet:
    context-path: /gym
spring:
  application:
    name: spring-gym-app
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${db_password}
    url: jdbc:postgresql://localhost:5432/${db_name}
    username: ${db_username}
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
    password: ${db_password}
    url: jdbc:postgresql://localhost:5432/${db_name}
    user: ${db_username}
  jpa:
    database: postgresql
    show-sql: false
jwt:
  secret: ${jwt_secret}
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org:
      example: debug
      hibernate:
        resource: error
      springframework:
        security: debug
    root: info

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10